rules:
  - metadata:
      kind: prequel
      id: SB5R34lt1m3C1nf1gErr1r
      gen: 1
    cre:
      id: CRE-2025-0140
      severity: 2
      title: "Supabase Self-Hosted: Realtime Service Crash Due to Invalid Configuration"
      category: "realtime-problem"
      author: Prequel
      description: |
        Detects when Supabase Realtime service fails to start or crashes due to invalid configuration parameters.
        This affects WebSocket connections, real-time subscriptions, and live data streaming capabilities.
        Common issues include invalid replication modes, missing database permissions, or incorrect environment variables.
      cause: |
        - Invalid REPLICATION_MODE configuration value
        - Incorrect database connection parameters for realtime
        - Missing or wrong DB_ENC_KEY encryption key
        - Invalid SECRET_KEY_BASE configuration
        - Insufficient database permissions for realtime operations
        - Wrong FLY_* configuration parameters in non-Fly environments
      tags:
        - supabase
        - realtime
        - configuration
        - replication
        - connection
        - self-hosted
        - configuration-failure
        - public
      mitigation: |
        IMMEDIATE:
          - Check realtime service logs: `docker-compose logs realtime`
          - Validate realtime environment variables in .env
          - Ensure database is accessible from realtime service
        CONFIGURATION:
          - Remove invalid REPLICATION_MODE if not using custom replication
          - Verify database connection settings:
            ```
            DB_HOST=db
            DB_PORT=5432
            DB_USER=supabase_realtime_admin
            ```
          - Set valid SECRET_KEY_BASE (64+ character random string)
          - Remove FLY_* variables if not deploying on Fly.io
        DATABASE:
          - Ensure realtime schema exists and has proper permissions
          - Check if supabase_realtime_admin role exists and has access
          - Verify _realtime schema is properly configured
      references:
        - https://supabase.com/docs/guides/realtime
        - https://github.com/supabase/realtime
      applications:
        - name: realtime
          containerName: supabase-realtime
          version: "v2.*"
      impact: |
        - Real-time subscriptions fail to connect
        - WebSocket connections are rejected
        - Live data updates stop working
        - Real-time features in applications become unavailable
        - Database change notifications are not delivered
      impactScore: 6
      mitigationScore: 5
      reports: 12
    rule:
      set:
        window: 5m
        event:
          source: cre.log.realtime
        match:
          - regex: 'invalid.*replication.*mode|REPLICATION_MODE.*unknown|realtime.*configuration.*error'
          - regex: 'SECRET_KEY_BASE.*invalid|DB_ENC_KEY.*missing|realtime.*startup.*failed'
          - regex: 'websocket.*connection.*failed|realtime.*service.*crash|elixir.*application.*failed'
          - value: "realtime"


